-- Add 15 sample clothing items for testing AI Fairy features
-- Replace 'YOUR_USER_ID' with your actual user ID from Supabase auth.users table

-- First, get your user ID by running this query in Supabase SQL editor:
-- SELECT id, email FROM auth.users WHERE email = 'your-email@example.com';

-- Then replace 'YOUR_USER_ID' below with the actual user ID

INSERT INTO clothing_items (
  user_id,
  image_url,
  category,
  subcategory,
  color,
  pattern,
  fabric,
  brand,
  size,
  season,
  formality,
  tags,
  purchase_date,
  purchase_price,
  notes,
  is_favorite,
  times_worn,
  created_at,
  updated_at
) VALUES 
-- Tops
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=600&fit=crop',
  'tops',
  'White T-shirt',
  'white',
  'solid',
  'cotton',
  'Uniqlo',
  'M',
  'all-year',
  'casual',
  ARRAY['basic', 'essential', 'comfortable'],
  '2024-01-15',
  15.99,
  'Perfect basic white tee',
  true,
  25,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&h=600&fit=crop',
  'tops',
  'Blue Button-up Shirt',
  'blue',
  'solid',
  'cotton',
  'Zara',
  'M',
  'all-year',
  'smart-casual',
  ARRAY['work', 'versatile', 'classic'],
  '2024-02-10',
  45.00,
  'Great for work and casual wear',
  true,
  18,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&h=600&fit=crop',
  'tops',
  'Black Hoodie',
  'black',
  'solid',
  'cotton',
  'Nike',
  'L',
  'fall',
  'casual',
  ARRAY['comfortable', 'sporty', 'warm'],
  '2023-11-20',
  65.00,
  'Super comfortable for lounging',
  true,
  30,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=600&fit=crop',
  'tops',
  'Striped Sweater',
  'navy',
  'striped',
  'wool',
  'H&M',
  'M',
  'winter',
  'casual',
  ARRAY['warm', 'classic', 'cozy'],
  '2023-12-05',
  35.00,
  'Perfect for winter days',
  false,
  12,
  NOW(),
  NOW()
),

-- Bottoms
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=600&fit=crop',
  'bottoms',
  'Dark Blue Jeans',
  'blue',
  'solid',
  'denim',
  'Levi''s',
  '32',
  'all-year',
  'casual',
  ARRAY['classic', 'versatile', 'comfortable'],
  '2024-01-20',
  89.99,
  'Perfect fit, great quality',
  true,
  40,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=600&fit=crop',
  'bottoms',
  'Black Chinos',
  'black',
  'solid',
  'cotton',
  'Banana Republic',
  '32',
  'all-year',
  'business-casual',
  ARRAY['work', 'professional', 'versatile'],
  '2024-02-15',
  79.99,
  'Great for office wear',
  true,
  22,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=600&fit=crop',
  'bottoms',
  'Gray Joggers',
  'gray',
  'solid',
  'cotton',
  'Adidas',
  'M',
  'all-year',
  'casual',
  ARRAY['comfortable', 'sporty', 'relaxed'],
  '2024-01-05',
  55.00,
  'Perfect for workouts and lounging',
  false,
  35,
  NOW(),
  NOW()
),

-- Dresses
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=600&fit=crop',
  'dresses',
  'Little Black Dress',
  'black',
  'solid',
  'polyester',
  'Zara',
  'M',
  'all-year',
  'formal',
  ARRAY['elegant', 'versatile', 'classic'],
  '2024-01-30',
  69.99,
  'Perfect for special occasions',
  true,
  8,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=600&fit=crop',
  'dresses',
  'Floral Summer Dress',
  'pink',
  'floral',
  'cotton',
  'H&M',
  'S',
  'summer',
  'casual',
  ARRAY['feminine', 'light', 'colorful'],
  '2024-03-10',
  39.99,
  'Great for summer days',
  false,
  15,
  NOW(),
  NOW()
),

-- Outerwear
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=600&fit=crop',
  'outerwear',
  'Denim Jacket',
  'blue',
  'solid',
  'denim',
  'Levi''s',
  'M',
  'all-year',
  'casual',
  ARRAY['classic', 'versatile', 'timeless'],
  '2023-10-15',
  95.00,
  'Goes with everything',
  true,
  28,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=600&fit=crop',
  'outerwear',
  'Black Blazer',
  'black',
  'solid',
  'wool',
  'H&M',
  'M',
  'all-year',
  'business',
  ARRAY['professional', 'elegant', 'formal'],
  '2024-02-20',
  89.99,
  'Perfect for meetings',
  true,
  12,
  NOW(),
  NOW()
),

-- Shoes
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=600&fit=crop',
  'shoes',
  'White Sneakers',
  'white',
  'solid',
  'canvas',
  'Converse',
  '9',
  'all-year',
  'casual',
  ARRAY['comfortable', 'versatile', 'classic'],
  '2024-01-10',
  65.00,
  'Go with everything',
  true,
  45,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=600&fit=crop',
  'shoes',
  'Black Ankle Boots',
  'black',
  'solid',
  'leather',
  'Zara',
  '9',
  'fall',
  'smart-casual',
  ARRAY['elegant', 'versatile', 'comfortable'],
  '2023-11-10',
  89.99,
  'Great for fall and winter',
  true,
  20,
  NOW(),
  NOW()
),
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=600&fit=crop',
  'shoes',
  'Brown Loafers',
  'brown',
  'solid',
  'leather',
  'H&M',
  '9',
  'all-year',
  'business-casual',
  ARRAY['professional', 'classic', 'comfortable'],
  '2024-02-05',
  75.00,
  'Perfect for office',
  false,
  15,
  NOW(),
  NOW()
),

-- Accessories
(
  'YOUR_USER_ID',
  'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=600&fit=crop',
  'accessories',
  'Black Leather Bag',
  'black',
  'solid',
  'leather',
  'Zara',
  'One Size',
  'all-year',
  'business-casual',
  ARRAY['elegant', 'versatile', 'practical'],
  '2024-01-25',
  45.00,
  'Perfect everyday bag',
  true,
  50,
  NOW(),
  NOW()
);

-- Verify the items were added
SELECT 
  subcategory,
  color,
  category,
  brand,
  is_favorite
FROM clothing_items 
WHERE user_id = 'YOUR_USER_ID'
ORDER BY created_at DESC;
