name: closet_fairy
description: "Your personal AI-powered fashion assistant. Discover style inspiration, manage your digital closet, and get personalized outfit suggestions with the magic of AI."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.0.4
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/Logos/
    - assets/Fonts/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/Fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/Fonts/Playfair_Display/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
    - family: Karla
      fonts:
        - asset: assets/Fonts/Karla/Karla-VariableFont_wght.ttf
        - asset: assets/Fonts/Karla/Karla-Italic-VariableFont_wght.ttf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logos/Logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/Logos/Logo.png"
    background_color: "#E6F3FF"
    theme_color: "#E6F3FF"
  windows:
    generate: true
    image_path: "assets/Logos/Logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/Logos/Logo.png"
