name: takeapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.0.4
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logos/
    - assets/Fonts/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/Fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/Fonts/Playfair_Display/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
    - family: Karla
      fonts:
        - asset: assets/Fonts/Karla/Karla-VariableFont_wght.ttf
        - asset: assets/Fonts/Karla/Karla-Italic-VariableFont_wght.ttf
          style: italic
